#!/bin/bash

source 'requests.sh'

add_category "Cats: Food"
add_category "Cats: saci"
add_category "Cats: Silicat"
add_category "Donations: declic.ro"
add_category "Donations: wikipedia"
add_category "Immediate Obligations: Electric"
add_category "Immediate Obligations: Gas"
add_category "Immediate Obligations: Groceries"
add_category "Immediate Obligations: Internet"
add_category "Immediate Obligations: kaka"
add_category "Immediate Obligations: Netflix"
add_category "Immediate Obligations: Phone"
add_category "Immediate Obligations: Rent/Mortgage"
add_category "Immediate Obligations: Stuff I Forgot to Budget For"
add_category "Immediate Obligations: Transportation"
add_category "Immediate Obligations: Water"
add_category "Inflow: To be Budgeted"
add_category "Just for Fun: Gaming"
add_category "Just for Fun: Lego"
add_category "Just for Fun: Music"
add_category "NET: google-storage"
add_category "NET: mihaiv.eu"
add_category "NET: mihaiv.info-gcloud"
add_category "Quality of Life Goals: gifts"
add_category "True Expenses: loans"
