#!/bin/bash

source 'requests.sh'

add_category "spital"
add_category "casa share"
add_category "wikipedia"
add_category "declic.ro"
add_category "saci"
add_category "Silicat"
add_category "Food"
add_category "Rent/Mortgage"
add_category "Electric"
add_category "Water"
add_category "Gas"
add_category "Internet"
add_category "Phone"
add_category "Netflix"
add_category "Groceries"
add_category "kaka"
add_category "Transportation"
add_category "Stuff I Forgot to Budget For"
add_category "loans"
add_category "YNAB"
add_category "BRD I"
add_category "BRD II"
add_category "BRD CC"
add_category "google-storage"
add_category "mihaiv.eu"
add_category "mihaiv.info"
add_category "mihaiv.info-gcloud"
add_category "mihai.pw"
add_category "antispo.net"
add_category "antispo.com"
add_category "Lego"
add_category "Dining Out"
add_category "Gaming"
add_category "Music"
add_category "Fun Money"
add_category "house stuff"
add_category "gifts"
add_category "Vacation"
add_category "Fitness"
add_category "Education"
add_category "Overdraft"

