#!/bin/bash

source 'requests.sh'

add_payee "amazon"
add_payee "asoc"
add_payee "auchan"
add_payee "brd"
add_payee "bringo"
add_payee "casa traditiei"
add_payee "dang"
add_payee "declic.ro"
add_payee "dic"
add_payee "eatandgo"
add_payee "emag"
add_payee "eon"
add_payee "foodpanda.ro"
add_payee "google"
add_payee "ioana"
add_payee "kfc"
add_payee "mxhost.ro"
add_payee "netflix"
add_payee "nurd"
add_payee "palas"
add_payee "pandora"
add_payee "Petro"
add_payee "radu"
add_payee "rds"
add_payee "sergiu"
add_payee "sony"
add_payee "Starting Balance"
add_payee "steam"
add_payee "taxi"
add_payee "Transfer : BRD"
add_payee "Transfer : Overdraft"
add_payee "Transfer : Revolut Lei"
add_payee "Transfer : Wally"
add_payee "twitch.tv"
add_payee "uber"
add_payee "various"
add_payee "Vodafone"
add_payee "wikipedia"
